{% set name = "phx-class-registry" %}
{% set version = "4.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/phx-class-registry-{{ version }}.tar.gz
  sha256: 6a7fe8568f9000ad1f90c9a81c5cb65ec20ee3b89b2aaab7a67e14dbb67e11d1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10,<4.0
    - setuptools
    - pip
  run:
    - python >=3.10.0,<4.0.0

test:
  imports:
    - class_registry
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/todofixthis/class-registry
  summary: Factory+Registry pattern for Python classes
  license: MIT
  license_file: LICENCE.txt

extra:
  recipe-maintainers:
    - freundTech
